# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Justin Wu
tagline: "Embedded Software Engineer"
description: 'Embedded Software Engineer'
# url: https://justinwu9090.github.io/justinwu9090/

author:
  name: "Justin Wu"
  url: https://www.linkedin.com/in/justindwu/

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/justinwu9090/justinwu9090

plugins: [jekyll-paginate]

gems: [jekyll-paginate]

paginate: 5

paginate_path: "page:num"

